<?php
namespace Multiple\Backend\Models;

use Phalcon\Mvc\Model;

class Login extends Model{
    public function getSource()
    {
        parent::getSource(); // TODO: Change the autogenerated stub
        return "users";
    }
}